<?php

namespace app\controllers;

use app\models\Department;
use app\models\Employee;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\web\Controller;

class BaseController extends Controller
{
    /**
     * Список сотрудников ['id'=>'Имя']
     * @var array
     */
    public $employees = [];
    /**
     * Список отделов ['id'=>'Наименование']
     * @var array
     */
    public $departments = [];

    /**
     * Нам нужны эти списки для форм, заполним их при инициализации
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->employees = ArrayHelper::map(Employee::find()->all(), 'id', 'name');
        $this->departments = ArrayHelper::map(Department::find()->all(), 'id', 'name');
    }

    /**
     * Ограничим доступ
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }
}